#ifndef CODEX_BOARD_CONFIG_H
#define CODEX_BOARD_CONFIG_H

#define PAGER_WS2812_PIN 16U
#define PAGER_BUZZER_PIN 14U
#define PAGER_DISPLAY_BLK_PIN 8U
#define PAGER_DISPLAY_DC_PIN 9U
#define PAGER_DISPLAY_RES_PIN 10U
#define PAGER_DISPLAY_SDA_PIN 11U
#define PAGER_DISPLAY_SCL_PIN 12U

#define PAGER_DISPLAY_WIDTH 240U
#define PAGER_DISPLAY_HEIGHT 240U
#define PAGER_DISPLAY_SPI_HZ 48000000U

#define PAGER_LINE_CAPACITY 96U
#define PAGER_LED_UPDATE_MS 10U

#endif
